### ISSUE TITLE
Support for Statamic Antlers

### ISSUE THREAD

**Issue by bgarrant** [wesbos/cobalt2-atom#17]
Is there any way to get better highlighting for Statamic Antlers syntax?  Please see https://atom.io/packages/language-antlers. Thank you.

![screen shot 2018-01-31 at 7 08 44 am](https://user-images.githubusercontent.com/2436728/35622431-d70f2586-0655-11e8-91a8-a2e53511f671.png)

**Comment by rosston** [comment]
Sorry, late response here.

This is really up to the language package since they choose what CSS class gets applied to what syntax. `blue_box` in this case is getting marked as a variable. If you change it to `entries:listing` to match the example in the language-antlers README, it gets marked as a function call and therefore gets a (presumably more desirable) yellow color.

<img width="663" alt="screen shot 2018-05-15 at 21 41 20" src="https://user-images.githubusercontent.com/108518/40091996-e038a2ba-5888-11e8-926e-4334450eeb22.png">

I know absolutely nothing about Statamic, so maybe those two things really are very different. I'm mostly just noting that it's up to the language package to put the appropriate CSS class on each piece of text so that themes don't have to know anything about individual languages.

I'm going to close this since I don't think the theme needs to do anything different, but I'm open to discussing it.
